---
dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  hexcolor: ^2.0.5
description: "A new Flutter project."
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  assets:
    - images/udx.jpeg
    - images/GqbZn29306.png
    - images/hello.png
    - images/abstract.jpg
  uses-material-design: true
name: udosxyz
publish_to: none
version: 1.0.0+1
